services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped

  backend:
    build: ./Server
    container_name: backend-container
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
      - /app/node_modules # ⚠️ Exclure node_modules
    depends_on:
      - mongodb
    env_file:
      - ./Server/.env
    restart: unless-stopped

